name: Templates

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-templates:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Pack templates
      run: dotnet build Rhino.Templates/Rhino.Templates.csproj

    - name: Generate and build every template
      run: dotnet msbuild build/GenerateTemplates.proj /p:RhinoInstalled=false
